apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"redis-cluster-0","cluster":"redis-cluster"},"name":"redis-cluster-0","namespace":"kdax-portal"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"redis-cluster-0"}},"strategy":{"type":"Recreate"},"template":{"metadata":{"labels":{"app":"redis-cluster-0","cluster":"redis-cluster"}},"spec":{"containers":[{"args":["/data/redis.conf"],"command":["redis-server"],"image":"redis:latest","name":"redis","ports":[{"containerPort":30005,"name":"client"},{"containerPort":40005,"name":"gossip"}],"volumeMounts":[{"mountPath":"/conf/","name":"redis-data"},{"mountPath":"/data","name":"redis-data"}]}],"nodeSelector":{"kubernetes.io/hostname":"kbsys-k8s-worker1"},"volumes":[{"configMap":{"name":"kdax-redis-cluster"},"name":"redis-conf"},{"name":"redis-data","persistentVolumeClaim":{"claimName":"data-redis-cluster-0"}}]}}}}
  creationTimestamp: "2021-03-09T07:58:52Z"
  generation: 1
  labels:
    app: redis-cluster-0
    cluster: redis-cluster
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
        f:labels:
          .: {}
          f:app: {}
          f:cluster: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector:
          f:matchLabels:
            .: {}
            f:app: {}
        f:strategy:
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
              f:cluster: {}
          f:spec:
            f:containers:
              k:{"name":"redis"}:
                .: {}
                f:args: {}
                f:command: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":30005,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                  k:{"containerPort":40005,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:name: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/conf/"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"/data"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:nodeSelector:
              .: {}
              f:kubernetes.io/hostname: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"redis-conf"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:name: {}
                f:name: {}
              k:{"name":"redis-data"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-09T07:58:52Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-03-15T01:30:59Z"
  name: redis-cluster-0
  namespace: kdax-portal
  resourceVersion: "29310542"
  selfLink: /apis/apps/v1/namespaces/kdax-portal/deployments/redis-cluster-0
  uid: da34de5e-655d-4b21-bec1-b85320c2938b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: redis-cluster-0
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: redis-cluster-0
        cluster: redis-cluster
    spec:
      containers:
      - args:
        - /data/redis.conf
        command:
        - redis-server
        image: redis:latest
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 30005
          name: client
          protocol: TCP
        - containerPort: 40005
          name: gossip
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /conf/
          name: redis-data
        - mountPath: /data
          name: redis-data
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: kbsys-k8s-worker1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kdax-redis-cluster
        name: redis-conf
      - name: redis-data
        persistentVolumeClaim:
          claimName: data-redis-cluster-0
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-03-09T07:58:53Z"
    lastUpdateTime: "2021-03-09T07:58:59Z"
    message: ReplicaSet "redis-cluster-0-756595bd8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-03-15T01:30:59Z"
    lastUpdateTime: "2021-03-15T01:30:59Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
