apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-cluster-node-30007","namespace":"kdax-portal"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"nodePort":30007,"port":30007,"protocol":"TCP","targetPort":30007}],"selector":{"app":"redis-cluster-1"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: "2021-03-09T06:41:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":30007,"protocol":"TCP"}:
            .: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-09T06:41:13Z"
  name: redis-cluster-node-30007
  namespace: kdax-portal
  resourceVersion: "26616104"
  selfLink: /api/v1/namespaces/kdax-portal/services/redis-cluster-node-30007
  uid: 41732cc1-ea31-4d07-8d34-c99c19c8c992
spec:
  clusterIP: 10.0.52.113
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30007
    port: 30007
    protocol: TCP
    targetPort: 30007
  selector:
    app: redis-cluster-1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
