apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-cluster-node-30008","namespace":"kdax-portal"},"spec":{"externalTrafficPolicy":"Cluster","ports":[{"nodePort":30008,"port":40007,"protocol":"TCP","targetPort":40007}],"selector":{"app":"redis-cluster-1"},"sessionAffinity":"None","type":"NodePort"}}
  creationTimestamp: "2021-03-09T06:41:13Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":40007,"protocol":"TCP"}:
            .: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-09T06:41:13Z"
  name: redis-cluster-node-30008
  namespace: kdax-portal
  resourceVersion: "26616110"
  selfLink: /api/v1/namespaces/kdax-portal/services/redis-cluster-node-30008
  uid: d7dcaba6-a317-4738-bfbb-54d481247556
spec:
  clusterIP: 10.0.36.9
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30008
    port: 40007
    protocol: TCP
    targetPort: 40007
  selector:
    app: redis-cluster-1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
