apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"redis-cluster-node","namespace":"kdax-portal"},"spec":{"ports":[{"nodePort":30002,"port":6379,"protocol":"TCP","targetPort":6379}],"selector":{"app":"redis-cluster"},"type":"NodePort"}}
  creationTimestamp: "2021-03-08T06:26:26Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ports:
          k:{"port":6379,"protocol":"TCP"}:
            .: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
    manager: kubectl-client-side-apply
    operation: Update
    time: "2021-03-04T07:09:14Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubectl.kubernetes.io/last-applied-configuration: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":30002,"protocol":"TCP"}:
            .: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":30003,"protocol":"TCP"}:
            .: {}
            f:nodePort: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: dashboard
    operation: Update
    time: "2021-03-08T06:26:26Z"
  name: redis-cluster-node-30002
  namespace: kdax-portal
  resourceVersion: "26129047"
  selfLink: /api/v1/namespaces/kdax-portal/services/redis-cluster-node-30002
  uid: 403f9ea4-c5d2-45d5-8edd-4a137f73561f
spec:
  clusterIP: 10.0.35.55
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30002
    port: 30002
    protocol: TCP
    targetPort: 30002
  selector:
    app: redis-cluster
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
